#!/usr/bin/env python
import os
import subprocess

currdir = os.path.dirname(os.path.realpath(__file__))
confdir = os.path.expanduser("~") + "/.config"

os.remove(confdir + "/i3/config")

os.symlink(currdir + "/i3/config", confdir + "/i3/config")

subprocess.run("i3-msg restart", shell=True)
